<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 -t -T -d true world.glb
-->

<script lang="ts">
  import type * as THREE from "three";

  import type { Snippet } from "svelte";
  import { T, type Props } from "@threlte/core";
  import { useGltf, useDraco } from "@threlte/extras";

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group;
    children?: Snippet<[{ ref: THREE.Group }]>;
    fallback?: Snippet;
    error?: Snippet<[{ error: Error }]>;
  } = $props();

  type GLTFResult = {
    nodes: {
      Earth: THREE.Mesh;
      Clouds: THREE.Mesh;
    };
    materials: {
      ["Material.001"]: THREE.MeshStandardMaterial;
      ["Material.003"]: THREE.MeshStandardMaterial;
    };
  };

  const gltf = useGltf<GLTFResult>("/world-transformed.glb", {
    dracoLoader: useDraco(),
  });
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Earth.geometry}
      material={gltf.materials["Material.001"]}
      rotation={[0.39, 0.65, 0]}
      scale={1.35}
    />
    <T.Mesh
      geometry={gltf.nodes.Clouds.geometry}
      material={gltf.materials["Material.003"]}
      rotation={[0.39, 0.65, 0]}
      scale={1.38}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
